# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 3.0.0.{build}

skip_commits:
  files:
   - '**/*.md'
   - .github/*

#---------------------------------#
#      environment configuration  #
#---------------------------------#

install:
  - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
  - ps: (Import-PowerShellDataFile "$env:APPVEYOR_BUILD_FOLDER\PowerStig.psd1").RequiredModules |
        ForEach-Object { Install-Module $PSItem.moduleName -RequiredVersion $PSItem.ModuleVersion -Repository PSGallery -Scope CurrentUser -Force }
  - git clone https://github.com/PowerShell/DscResource.Tests
  - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
  - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\Tools\AppVeyor\AppVeyor.psm1"
  - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @('tools')

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# Scripts to run before deployment
before_deploy:
  - ps: Invoke-PowerStigAppveyorAfterTestTask

for:
-
  branches:
    only:
      - master

  deploy:
    - provider: Environment
      name: Test PS Gallery
      on:
        appveyor_repo_tag: true
